enyo.kind({
	name:"enyo.WebView",
	kind:enyo.Control,
	classes:"enyo-webview",
	published:{
		tag:"iframe",
		src:"about:blank",
	},
	srcChanged:function()
	{
		this.inherited(arguments);
		this.setNodeProperty("src",this.getSrc());
	},
	create:function()
	{
		this.inherited(arguments);
		webview = this;
	},
});
